### ISSUE TITLE
does not delete files

### ISSUE THREAD

**Issue by cr1stt0f3r** [ticgal/gapp#15]
when uploading files or photos using the application, there is no option to delete this file.
The web version is also funny, as the delete button is transparent, almost invisible.

Is this adjustment possible?

**Comment by PedroTicGal** [comment]
Hi @cr1stt0f3r,

First of all, thank you for using Gapp and taking time to give us feedback about it!

If you are talking about deleting documents after uploading to GLPI, Gapp doesn't support yet this feature. Since we are offering Gapp for free, the launch of new releases and features will come slower than we'd love.

Anyway, this adjustment is possible if someone is willing to sponsor it. =)

We'd like to thank you again for giving us feedback and we'd be very grateful if you could rate Gapp on [Google Play](https://play.google.com/store/apps/details?id=gal.tic.gapp.selfservice) to help us spread the word!

Cheers!

**Comment by OscarBeiro** [comment]
This is too dangerous to be performed from an app.
You can choose what images you upload before actually uploading then.
I don't think we will add a delete option from the mobile tool.

Regards,
