### ISSUE TITLE
Prohibited translation licensing change

### ISSUE THREAD

**Issue by comradekingu** [ticgal/gapp#17]
https://hosted.weblate.org/projects/gapp/gapp-selfservice/#information
was changed from AGPLv3+ to Creative Commons Attribution 4.0 International without consulting the rights-holders to the translations, which is the respective translators.

This is no longer me, as my translations were deleted, but alas.

**Comment by OscarBeiro** [comment]
Hi,

As a result of your indications, we have changed the licensing of the translations. We asked a lawyer and he told us to change to the current license. 
These are the actions we have taken to mitigate our mistake:

1. We have removed completely your translation Norwegian Bokmål, a month ago, as you asked.
2. Added a note to the Translation component, visible on access.
3. Added additional information to new translators, to avoid future misunderstandings. 
4. A request has been sent to Weblate support, asking for a simple way to notify translators. As you are aware, there is no easy way to do this from within weblate, since we don't have access to translators emails.

Is there anything more we can do for you?

**Comment by comradekingu** [comment]
1. As noted, this does no longer concern me, for that reason.
2. The problem is you need the consent of the copyright holders to re-license the way you did.
3. That is good for translations following the change.
4. You do have that access. It is both in the commit logs, and in the generated contribution lists.

Please send compensation for my time making spent making a Norwegian Bokmål translation in any prior distributed versions (if any) to Weblate.

Edit: You might also want to research the legality of using AGPLv3+ code with closed source in the way you are doing it.
It is quite telling how you didn't just license everything AGPLV3+, but instead put yourselves in this less-than-stellar situation.

Edit2: It is not primarily a documentation issue, it is a legality issue. You are undermining the license you are using.

**Comment by PedroTicGal** [comment]
Hi Allan,

First of all, thank you for your time and feedback.

As you noted in your reply, we had a problem/misunderstood with the licence in "weblate". Once we realized the mistake, we changed it, but obviously, we cannot change the licence of translations that people did in this repository without their consent.

We cannot get email addresses from commit log since we are using a hosted Weblate, but thanks to you we realized that we could get the emails from the translation reports.

That said, regarding licencing:

We are the creators of English, Spanish and Galician translations. Most of Portuguese too.
We recovered the French and Russian translation from our last translation platform, in which we had a privative licence, adding credits for all translators in our web. For everyone interested in it. [https://tic.gal/en/gapp-kudos/](https://tic.gal/en/gapp-kudos/)

We asked the translators who contributed here in Weblate by email if they were agree with the licence and everyone agreed.

Since we are developing our app "Gapp SelfService" free of charge, we don't get paid for it. We don't monetize it with any advertising service, nor we don't steal/take any information about any user in order to sell it to anyone. Shamefully, we cannot give you any compensation for your time, more than giving you our most truly thanks to you for doing it in such an altruistic way.

This is a project trying to solve a problem: GLPI not having an Android client. A few kind GLPI users around the world understood this and asked to translate it to have it in their mother tongues willing no reward more than seeing the app translated.

We believe this problem is resolved. Therefore, we close it.
