### ISSUE TITLE
When logging into Gapp, a blank popup appears

### ISSUE THREAD

**Issue by fmanfredini** [ticgal/gapp#19]
When closing the popup it returns to the login screen
Version Android - 8.1.0
GAPP - Version 1.0.7.11 - Selfservice-beta

**Your GLPI server**
 - GLPI Version: GLPI 9.4.4 
 - Installed plugins: Gapp Essentials 1.1.0 

**Additional context**
The problem started to occur in the last app update

**Comment by OscarBeiro** [comment]
Hi @fmanfredini,
Thanks for using Gapp.
This is not a bug. This is your environment returning than GLPI would do.
Gapp is parsing returned response,  trying to throw some light on your problem, but definitely not GLPI.

You need to start looking at your web server logs, firewall or any other device/appliance/service that is blocking communication between Gapp and GLPI.

We would appreciate telling us what it is when you find out since it would help future users having the same message.

Regards,

**Comment by OscarBeiro** [comment]
For future reference, we have added more information here: https://tic.gal/en/white-pop-up-when-login-into-gapp-doesnt-allow-login/
