### ISSUE TITLE
ERROR TIME OUT

### ISSUE THREAD

**Issue by ilmc2001** [ticgal/gapp#24]
Hello I get several time out error on Gapp self service.

What can I do to solve this?

Luis Cunha

**Comment by gitsyncuser** [comment]
<p><p dir=\"ltr\">Olá Luis,  </p><p dir=\"ltr\">We are aware of this issue. It is due to a slow GLPI SERVER.<br>Timeout is hard-coded on Gapp 1.1 but we have added a new setting  on upcoming 1.2. to allow increasing it. </p><p dir=\"ltr\">Obrigado pelo uso do Gapp</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

![Screenshot_20200903_083009_gal tic gapp selfservice](https://user-images.githubusercontent.com/18396050/92079703-a8d11580-edc0-11ea-8d24-2f3a57ffb841.jpg)

**Comment by ilmc2001** [comment]
Ok Thanks

I have 1.1.3 version can wait for upcoming 1.2.

By

Luis Cunha
