### ISSUE TITLE
Problem launching the GAPP application

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [ticgal/gapp#48]
**Is your feature request related to an issue? Please describe.**

Since our upgrade to version 10.0.4-dev, the GAPP application displays the error concerning CVE-2022-35914 and CVE-2022-35947.

**Describe the solution you want**

We would like the application to detect that our version of GLPI is above version 10.0.3

**Describe the alternatives you have considered**

A return to version 10.0.3 fixes the problem.

**Additional Context**
Image of our version of GLPI:

![image](https://user-images.githubusercontent.com/91662361/196991493-7677e46e-0e80-4daa-a3a2-65209bb09714.png)

GAPP app picture:

![Screenshot_20221020-172453](https://user-images.githubusercontent.com/91662361/196991547-d40d08f1-0b9d-4fc2-bf7c-c3e933e37ebb.jpg)

**Comment by PedroTicGal** [comment]
Hi @TestOrganigrammeBA,

First of all, thank you for using Gapp and contacting us with your feedback.

As far as we know, this problem must be related to the "-dev" suffix in the GLPI version naming.

In every new version of GLPI there are several changes that "break" Gapp and therefore we have to fix it to make it work smoothly. Gapp will probably not work correctly in a dev version of GLPI.

Unfortunately, because of this we are not supporting dev versions.

Sorry for the inconvenience.
