### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [ticgal/gapp#56]
**Sponsor a feature**
If you are ready to sponsor a feature, or would like a custom feature, contact us at https://tic.gal/, otherwise please fill in the requested information

**Is your feature request related to an issue?

It puts impossible to connect to the application, and this since I set up the SSO on GLPI.
However, I authorized the API file without SSO.

Here is a screenshot of the app:

![Screenshot_20230123_105933](https://user-images.githubusercontent.com/91662361/214013790-abfc3624-004e-46ec-a5af-6539c1e1c240.jpg)

**Describe the solution you want**
I wish I could log into the app and be able to use it like before.

**Comment by OscarBeiro** [comment]
Hi,

The HTML tag shows that the API is not accessed freely.
There is something in between the app and GLPI API. Nothing related to GLPI or Gapp.

If you want to use SSO we have a White Label solution. You can contact us through our website https://tic.gal

Otherwise you need to debug what is blocking the access.

Regards,
