### ISSUE TITLE
[Bug] Attachement Not Acceptable

### ISSUE THREAD

**Issue by jcovillers78114** [ticgal/gapp#67]
Hello,
When I take a photo directly from the application in a ticket response, I get an unacceptable error. Same thing if I want to manually add an attachment.

![Screenshot_2024-01-17-16-38-37-139_gal tic gapp selfservice](https://github.com/ticgal/gapp/assets/57490677/2afc2333-b52d-4222-b55d-1c668a450d07)

**Comment by dantesarotti** [comment]
Hello,
we have tried to replicate this error in the test server but it's working fine for us.
"Not acceptable" refers to an apache client error response code 406 which means that the server can not answer the request.
This is most probably an error caused by a wrong configuration of the server, either on apache or glpi.

**Comment by jcovillers78114** [comment]
Hello,
Thank you for your reply.
What do you recommend regarding this error, which only occurs when using gapp?

**Comment by dantesarotti** [comment]
Your issue could be caused by several factors.
Is your image bigger than the max size you have configured in your GLPI? 
Is there any configuration on your server that may be restricting uploads?

Other causes may be related with compatibility within versions.
GLPI version ?
Gapp Essentials version ?
Gapp version ?

We recommend at least update Gapp and Essentials to the latest version.
