### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by tguichard25** [ticgal/gapp#7]
**Describe the bug**
Unable to login

**Screenshots**
![image](https://user-images.githubusercontent.com/47602797/67768823-a04ad880-fa53-11e9-9079-6cec5c8839ed.png)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy A7
 - OS: 9

**Your GLPI server**
 - GLPI Version: 9.4.4
 - Installed plugins:
![image](https://user-images.githubusercontent.com/47602797/67768538-0c790c80-fa53-11e9-9fc1-99854c0caf61.png)

**Comment by OscarBeiro** [comment]
Hi,
A few questions:

1. Can you connect to the demo server?

1. Did you follow every step of the manual? https://tic.gal/en/project/gapp/

Please note, you have to add complete server name. If you server is **http://glpiserver.tld/glpi** you must add **glpiserver.tld/glpi** to Gapp.

**Comment by tguichard25** [comment]
1. Yes I can
2.I followed all the steps. I can access the API page from a browser.

My server is accessible from the root of the server. I checked the address several times in "General configuration".
 http://glpiserver.tld/

**Comment by OscarBeiro** [comment]
Hi,
We've been thinking about this issue, and looks like #3.
Most probably a firewall rule is blocking something it shouldn't.

If you want to debug it, please close the ticket. If you want us to help you since we are willing to document the widest possible scenarios to help users fix them, I'm offering you, additional debugging time.

We would need you to create a self-service user, and provide the pass and of course, server address.
Set Valid until today at 15h. It would be enough for us to test.

Just write it here, and after saving, delete all these 3 data. We will receive an email notification, and your data won't be exposed.

Regards,

**Comment by OscarBeiro** [comment]
Closed due to inactivity
